
use pain;

drop table traffic_cities;

create table traffic_cities (
    id int primary key auto_increment,
    city varchar(255),
    state varchar(255),
    disabled int not null default 0,
    nextcheck TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

insert into traffic_cities (city,state) values ('Houston','TX');
insert into traffic_cities (city,state) values ('Orlando','FL');
insert into traffic_cities (city,state) values ('New York','NY');
insert into traffic_cities (city,state) values ('Los Angeles','CA');
insert into traffic_cities (city,state) values ('Chicago','IL');
insert into traffic_cities (city,state) values ('Phoenix','AZ');
insert into traffic_cities (city,state) values ('Philadelphia','PA');
insert into traffic_cities (city,state) values ('San Antonio','TX');
insert into traffic_cities (city,state) values ('San Diego','CA');
insert into traffic_cities (city,state) values ('Dallas','TX');
insert into traffic_cities (city,state) values ('Austin','TX');
insert into traffic_cities (city,state) values ('Jacksonville','FL');
insert into traffic_cities (city,state) values ('San Jose','CA');
insert into traffic_cities (city,state) values ('Fort Worth','TX');
insert into traffic_cities (city,state) values ('Columbus','OH');
insert into traffic_cities (city,state) values ('Charlotte','NC');
insert into traffic_cities (city,state) values ('Indianapolis','IN');
insert into traffic_cities (city,state) values ('San Francisco','CA');
insert into traffic_cities (city,state) values ('Seattle','WA');
insert into traffic_cities (city,state) values ('Denver','CO');
insert into traffic_cities (city,state) values ('Oklahoma City','OK');
insert into traffic_cities (city,state) values ('Nashville','TN');
insert into traffic_cities (city,state) values ('El Paso','TX');
insert into traffic_cities (city,state) values ('Washington','DC');
insert into traffic_cities (city,state) values ('Las Vegas','NV');
insert into traffic_cities (city,state) values ('Boston','MA');
insert into traffic_cities (city,state) values ('Portland','OR');
insert into traffic_cities (city,state) values ('Louisville','KY');
insert into traffic_cities (city,state) values ('Memphis','TN');
insert into traffic_cities (city,state) values ('Detroit','MI');
insert into traffic_cities (city,state) values ('Baltimore','MD');
insert into traffic_cities (city,state) values ('Milwaukee','WI');
insert into traffic_cities (city,state) values ('Albuquerque','NM');
insert into traffic_cities (city,state) values ('Tucson','AZ');
insert into traffic_cities (city,state) values ('Fresno','CA');
insert into traffic_cities (city,state) values ('Sacramento','CA');
insert into traffic_cities (city,state) values ('Mesa','AZ');
insert into traffic_cities (city,state) values ('Kansas City','MO');
insert into traffic_cities (city,state) values ('Atlanta','GA');
insert into traffic_cities (city,state) values ('Colorado Springs','CO');
insert into traffic_cities (city,state) values ('Omaha','NE');
insert into traffic_cities (city,state) values ('Raleigh','NC');
insert into traffic_cities (city,state) values ('Virginia Beach','VA');
insert into traffic_cities (city,state) values ('Long Beach','CA');
insert into traffic_cities (city,state) values ('Miami','FL');
insert into traffic_cities (city,state) values ('Oakland','CA');
insert into traffic_cities (city,state) values ('Minneapolis','MN');
insert into traffic_cities (city,state) values ('Tulsa','OK');
insert into traffic_cities (city,state) values ('Bakersfield','CA');
insert into traffic_cities (city,state) values ('Tampa','FL');
insert into traffic_cities (city,state) values ('Wichita','KS');
insert into traffic_cities (city,state) values ('Arlington','TX');
insert into traffic_cities (city,state) values ('Aurora','CO');
insert into traffic_cities (city,state) values ('New Orleans','LA');
insert into traffic_cities (city,state) values ('Cleveland','OH');
insert into traffic_cities (city,state) values ('Anaheim','CA');
insert into traffic_cities (city,state) values ('Honolulu','HI');
insert into traffic_cities (city,state) values ('Henderson','NV');
insert into traffic_cities (city,state) values ('Stockton','CA');
insert into traffic_cities (city,state) values ('Riverside','CA');
insert into traffic_cities (city,state) values ('Lexington','KY');
insert into traffic_cities (city,state) values ('Corpus Christi','TX');
insert into traffic_cities (city,state) values ('Irvine','CA');
insert into traffic_cities (city,state) values ('Cincinnati','OH');
insert into traffic_cities (city,state) values ('Santa Ana','CA');
insert into traffic_cities (city,state) values ('Newark','NJ');
insert into traffic_cities (city,state) values ('Saint Paul','MN');
insert into traffic_cities (city,state) values ('Pittsburgh','PA');
insert into traffic_cities (city,state) values ('Greensboro','NC');
insert into traffic_cities (city,state) values ('Lincoln','NE');
insert into traffic_cities (city,state) values ('Durham','NC');
insert into traffic_cities (city,state) values ('Plano','TX');
insert into traffic_cities (city,state) values ('Anchorage','AK');
insert into traffic_cities (city,state) values ('Jersey City','NJ');
insert into traffic_cities (city,state) values ('St. Louis','MO');
insert into traffic_cities (city,state) values ('Chandler','AZ');
insert into traffic_cities (city,state) values ('North Las Vegas','NV');
insert into traffic_cities (city,state) values ('Chula Vista','CA');
insert into traffic_cities (city,state) values ('Buffalo','NY');
insert into traffic_cities (city,state) values ('Gilbert','AZ');
insert into traffic_cities (city,state) values ('Reno','NV');
insert into traffic_cities (city,state) values ('Madison','WI');
insert into traffic_cities (city,state) values ('Fort Wayne','IN');
insert into traffic_cities (city,state) values ('Toledo','OH');
insert into traffic_cities (city,state) values ('Lubbock','TX');
insert into traffic_cities (city,state) values ('St. Petersburg','FL');
insert into traffic_cities (city,state) values ('Laredo','TX');
insert into traffic_cities (city,state) values ('Irving','TX');
insert into traffic_cities (city,state) values ('Chesapeake','VA');
insert into traffic_cities (city,state) values ('Glendale','AZ');
insert into traffic_cities (city,state) values ('Winston-Salem','NC');
insert into traffic_cities (city,state) values ('Scottsdale','AZ');
insert into traffic_cities (city,state) values ('Garland','TX');
insert into traffic_cities (city,state) values ('Boise','ID');
insert into traffic_cities (city,state) values ('Norfolk','VA');
insert into traffic_cities (city,state) values ('Port St. Lucie','FL');
insert into traffic_cities (city,state) values ('Spokane','WA');
insert into traffic_cities (city,state) values ('Richmond','VA');
insert into traffic_cities (city,state) values ('Fremont','CA');
insert into traffic_cities (city,state) values ('Huntsville','AL');
insert into traffic_cities (city,state) values ('Tacoma','WA');
insert into traffic_cities (city,state) values ('Baton Rouge','LA');
insert into traffic_cities (city,state) values ('Santa Clarita','CA');
insert into traffic_cities (city,state) values ('San Bernardino','CA');
insert into traffic_cities (city,state) values ('Hialeah','FL');
insert into traffic_cities (city,state) values ('Frisco','TX');
insert into traffic_cities (city,state) values ('Modesto','CA');
insert into traffic_cities (city,state) values ('Cape Coral','FL');
insert into traffic_cities (city,state) values ('Fontana','CA');
insert into traffic_cities (city,state) values ('Moreno Valley','CA');
insert into traffic_cities (city,state) values ('Des Moines','IA');
insert into traffic_cities (city,state) values ('Rochester','NY');
insert into traffic_cities (city,state) values ('Fayetteville','NC');
insert into traffic_cities (city,state) values ('Yonkers','NY');
insert into traffic_cities (city,state) values ('McKinney','TX');
insert into traffic_cities (city,state) values ('Worcester','MA');
insert into traffic_cities (city,state) values ('Salt Lake City','UT');
insert into traffic_cities (city,state) values ('Little Rock','AR');
insert into traffic_cities (city,state) values ('Columbus','GA');
insert into traffic_cities (city,state) values ('Augusta','GA');
insert into traffic_cities (city,state) values ('Sioux Falls','SD');
insert into traffic_cities (city,state) values ('Grand Prairie','TX');
insert into traffic_cities (city,state) values ('Tallahassee','FL');
insert into traffic_cities (city,state) values ('Amarillo','TX');
insert into traffic_cities (city,state) values ('Oxnard','CA');
insert into traffic_cities (city,state) values ('Peoria','AZ');
insert into traffic_cities (city,state) values ('Overland Park','KS');
insert into traffic_cities (city,state) values ('Montgomery','AL');
insert into traffic_cities (city,state) values ('Birmingham','AL');
insert into traffic_cities (city,state) values ('Grand Rapids','MI');
insert into traffic_cities (city,state) values ('Knoxville','TN');
insert into traffic_cities (city,state) values ('Vancouver','WA');
insert into traffic_cities (city,state) values ('Huntington Beach','CA');
insert into traffic_cities (city,state) values ('Providence','RI');
insert into traffic_cities (city,state) values ('Brownsville','TX');
insert into traffic_cities (city,state) values ('Glendale','CA');
insert into traffic_cities (city,state) values ('Akron','OH');
insert into traffic_cities (city,state) values ('Tempe','AZ');
insert into traffic_cities (city,state) values ('Newport News','VA');
insert into traffic_cities (city,state) values ('Chattanooga','TN');
insert into traffic_cities (city,state) values ('Mobile','AL');
insert into traffic_cities (city,state) values ('Fort Lauderdale','FL');
insert into traffic_cities (city,state) values ('Cary','NC');
insert into traffic_cities (city,state) values ('Shreveport','LA');
insert into traffic_cities (city,state) values ('Ontario','CA');
insert into traffic_cities (city,state) values ('Eugene','OR');
insert into traffic_cities (city,state) values ('Aurora','IL');
insert into traffic_cities (city,state) values ('Elk Grove','CA');
insert into traffic_cities (city,state) values ('Salem','OR');
insert into traffic_cities (city,state) values ('Santa Rosa','CA');
insert into traffic_cities (city,state) values ('Clarksville','TN');
insert into traffic_cities (city,state) values ('Rancho Cucamonga','CA');
insert into traffic_cities (city,state) values ('Oceanside','CA');
insert into traffic_cities (city,state) values ('Springfield','MO');
insert into traffic_cities (city,state) values ('Pembroke Pines','FL');
insert into traffic_cities (city,state) values ('Garden Grove','CA');
insert into traffic_cities (city,state) values ('Fort Collins','CO');
insert into traffic_cities (city,state) values ('Lancaster','CA');
insert into traffic_cities (city,state) values ('Palmdale','CA');
insert into traffic_cities (city,state) values ('Murfreesboro','TN');
insert into traffic_cities (city,state) values ('Salinas','CA');
insert into traffic_cities (city,state) values ('Corona','CA');
insert into traffic_cities (city,state) values ('Killeen','TX');
insert into traffic_cities (city,state) values ('Hayward','CA');
insert into traffic_cities (city,state) values ('Paterson','NJ');
insert into traffic_cities (city,state) values ('Macon','GA');
insert into traffic_cities (city,state) values ('Lakewood','CO');
insert into traffic_cities (city,state) values ('Alexandria','VA');
insert into traffic_cities (city,state) values ('Roseville','CA');
insert into traffic_cities (city,state) values ('Surprise','AZ');
insert into traffic_cities (city,state) values ('Springfield','MA');
insert into traffic_cities (city,state) values ('Charleston','SC');
insert into traffic_cities (city,state) values ('Kansas City','KS');
insert into traffic_cities (city,state) values ('Sunnyvale','CA');
insert into traffic_cities (city,state) values ('Bellevue','WA');
insert into traffic_cities (city,state) values ('Hollywood','FL');
insert into traffic_cities (city,state) values ('Denton','TX');
insert into traffic_cities (city,state) values ('Escondido','CA');
insert into traffic_cities (city,state) values ('Joliet','IL');
insert into traffic_cities (city,state) values ('Naperville','IL');
insert into traffic_cities (city,state) values ('Bridgeport','CT');
insert into traffic_cities (city,state) values ('Savannah','GA');
insert into traffic_cities (city,state) values ('Mesquite','TX');
insert into traffic_cities (city,state) values ('Pasadena','TX');
insert into traffic_cities (city,state) values ('Rockford','IL');
insert into traffic_cities (city,state) values ('Pomona','CA');
insert into traffic_cities (city,state) values ('Jackson','MS');
insert into traffic_cities (city,state) values ('Olathe','KS');
insert into traffic_cities (city,state) values ('Gainesville','FL');
insert into traffic_cities (city,state) values ('McAllen','TX');
insert into traffic_cities (city,state) values ('Syracuse','NY');
insert into traffic_cities (city,state) values ('Waco','TX');
insert into traffic_cities (city,state) values ('Visalia','CA');
insert into traffic_cities (city,state) values ('Thornton','CO');
insert into traffic_cities (city,state) values ('Torrance','CA');
insert into traffic_cities (city,state) values ('Fullerton','CA');
insert into traffic_cities (city,state) values ('Columbia','SC');
insert into traffic_cities (city,state) values ('Lakewood','NJ');
insert into traffic_cities (city,state) values ('New Haven','CT');
insert into traffic_cities (city,state) values ('Hampton','VA');
insert into traffic_cities (city,state) values ('Miramar','FL');
insert into traffic_cities (city,state) values ('Victorville','CA');
insert into traffic_cities (city,state) values ('Warren','MI');
insert into traffic_cities (city,state) values ('West Valley City','UT');
insert into traffic_cities (city,state) values ('Cedar Rapids','IA');
insert into traffic_cities (city,state) values ('Stamford','CT');
insert into traffic_cities (city,state) values ('Orange','CA');
insert into traffic_cities (city,state) values ('Dayton','OH');
insert into traffic_cities (city,state) values ('Midland','TX');
insert into traffic_cities (city,state) values ('Kent','WA');
insert into traffic_cities (city,state) values ('Elizabeth','NJ');
insert into traffic_cities (city,state) values ('Pasadena','CA');
insert into traffic_cities (city,state) values ('Carrollton','TX');
insert into traffic_cities (city,state) values ('Coral Springs','FL');
insert into traffic_cities (city,state) values ('Sterling Heights','MI');
insert into traffic_cities (city,state) values ('Fargo','ND');
insert into traffic_cities (city,state) values ('Lewisville','TX');
insert into traffic_cities (city,state) values ('Meridian','ID');
insert into traffic_cities (city,state) values ('Norman','OK');
insert into traffic_cities (city,state) values ('Palm Bay','FL');
insert into traffic_cities (city,state) values ('Athens','GA');
insert into traffic_cities (city,state) values ('Columbia','MO');
insert into traffic_cities (city,state) values ('Abilene','TX');
insert into traffic_cities (city,state) values ('Pearland','TX');
insert into traffic_cities (city,state) values ('Santa Clara','CA');
insert into traffic_cities (city,state) values ('Round Rock','TX');
insert into traffic_cities (city,state) values ('Topeka','KS');
insert into traffic_cities (city,state) values ('Allentown','PA');
insert into traffic_cities (city,state) values ('Clovis','CA');
insert into traffic_cities (city,state) values ('Simi Valley','CA');
insert into traffic_cities (city,state) values ('College Station','TX');
insert into traffic_cities (city,state) values ('Thousand Oaks','CA');
insert into traffic_cities (city,state) values ('Vallejo','CA');
insert into traffic_cities (city,state) values ('Concord','CA');
insert into traffic_cities (city,state) values ('Rochester','MN');
insert into traffic_cities (city,state) values ('Arvada','CO');
insert into traffic_cities (city,state) values ('Lafayette','LA');
insert into traffic_cities (city,state) values ('Independence','MO');
insert into traffic_cities (city,state) values ('West Palm Beach','FL');
insert into traffic_cities (city,state) values ('Hartford','CT');
insert into traffic_cities (city,state) values ('Wilmington','NC');
insert into traffic_cities (city,state) values ('Lakeland','FL');
insert into traffic_cities (city,state) values ('Billings','MT');
insert into traffic_cities (city,state) values ('Ann Arbor','MI');
insert into traffic_cities (city,state) values ('Fairfield','CA');
insert into traffic_cities (city,state) values ('Berkeley','CA');
insert into traffic_cities (city,state) values ('Richardson','TX');
insert into traffic_cities (city,state) values ('North Charleston','SC');
insert into traffic_cities (city,state) values ('Cambridge','MA');
insert into traffic_cities (city,state) values ('Broken Arrow','OK');
insert into traffic_cities (city,state) values ('Clearwater','FL');
insert into traffic_cities (city,state) values ('West Jordan','UT');
insert into traffic_cities (city,state) values ('Evansville','IN');
insert into traffic_cities (city,state) values ('League City','TX');
insert into traffic_cities (city,state) values ('Antioch','CA');
insert into traffic_cities (city,state) values ('Manchester','NH');
insert into traffic_cities (city,state) values ('High Point','NC');
insert into traffic_cities (city,state) values ('Waterbury','CT');
insert into traffic_cities (city,state) values ('Westminster','CO');
insert into traffic_cities (city,state) values ('Richmond','CA');
insert into traffic_cities (city,state) values ('Carlsbad','CA');
insert into traffic_cities (city,state) values ('Las Cruces','NM');
insert into traffic_cities (city,state) values ('Murrieta','CA');
insert into traffic_cities (city,state) values ('Lowell','MA');
insert into traffic_cities (city,state) values ('Provo','UT');
insert into traffic_cities (city,state) values ('Springfield','IL');
insert into traffic_cities (city,state) values ('Elgin','IL');
insert into traffic_cities (city,state) values ('Odessa','TX');
insert into traffic_cities (city,state) values ('Lansing','MI');
insert into traffic_cities (city,state) values ('Pompano Beach','FL');
insert into traffic_cities (city,state) values ('Beaumont','TX');
insert into traffic_cities (city,state) values ('Temecula','CA');
insert into traffic_cities (city,state) values ('Gresham','OR');
insert into traffic_cities (city,state) values ('Allen','TX');
insert into traffic_cities (city,state) values ('Pueblo','CO');
insert into traffic_cities (city,state) values ('Everett','WA');
insert into traffic_cities (city,state) values ('South Fulton','GA');
insert into traffic_cities (city,state) values ('Peoria','IL');
insert into traffic_cities (city,state) values ('Nampa','ID');
insert into traffic_cities (city,state) values ('Tuscaloosa','AL');
insert into traffic_cities (city,state) values ('Miami Gardens','FL');
insert into traffic_cities (city,state) values ('Santa Maria','CA');
insert into traffic_cities (city,state) values ('Downey','CA');
insert into traffic_cities (city,state) values ('Concord','NC');
insert into traffic_cities (city,state) values ('Ventura','CA');
insert into traffic_cities (city,state) values ('Costa Mesa','CA');
insert into traffic_cities (city,state) values ('Sugar Land','TX');
insert into traffic_cities (city,state) values ('Menifee','CA');
insert into traffic_cities (city,state) values ('Tyler','TX');
insert into traffic_cities (city,state) values ('Sparks','NV');
insert into traffic_cities (city,state) values ('Greeley','CO');
insert into traffic_cities (city,state) values ('Rio Rancho','NM');
insert into traffic_cities (city,state) values ('Sandy Springs','GA');
insert into traffic_cities (city,state) values ('Dearborn','MI');
insert into traffic_cities (city,state) values ('Jurupa Valley','CA');
insert into traffic_cities (city,state) values ('Edison','NJ');
insert into traffic_cities (city,state) values ('Spokane Valley','WA');
insert into traffic_cities (city,state) values ('Hillsboro','OR');
insert into traffic_cities (city,state) values ('Davie','FL');
insert into traffic_cities (city,state) values ('Green Bay','WI');
insert into traffic_cities (city,state) values ('Centennial','CO');
insert into traffic_cities (city,state) values ('Buckeye','AZ');
insert into traffic_cities (city,state) values ('Boulder','CO');
insert into traffic_cities (city,state) values ('Goodyear','AZ');
insert into traffic_cities (city,state) values ('El Monte','CA');
insert into traffic_cities (city,state) values ('West Covina','CA');
insert into traffic_cities (city,state) values ('Brockton','MA');
insert into traffic_cities (city,state) values ('New Braunfels','TX');
insert into traffic_cities (city,state) values ('El Cajon','CA');
insert into traffic_cities (city,state) values ('Edinburg','TX');
insert into traffic_cities (city,state) values ('Renton','WA');
insert into traffic_cities (city,state) values ('Burbank','CA');
insert into traffic_cities (city,state) values ('Inglewood','CA');
insert into traffic_cities (city,state) values ('Rialto','CA');
insert into traffic_cities (city,state) values ('Lee''s Summit','MO');
insert into traffic_cities (city,state) values ('Bend','OR');
insert into traffic_cities (city,state) values ('Woodbridge','NJ');
insert into traffic_cities (city,state) values ('South Bend','IN');
insert into traffic_cities (city,state) values ('Wichita Falls','TX');
