
use pain;
create table timezones (
    id int primary key auto_increment,
    abbrev varchar(15),
    name varchar(255),
    location varchar(255),
    offset varchar(50)
);

insert into timezones (abbrev,name,location,offset) values
('CST','Central Standard Time','North America','-6'),
('ADT','Atlantic Daylight Time','North America','-3'),
('AKDT','Alaska Daylight Time','North America','-8'),
('AKST','Alaska Standard Time','North America','-9'),
('AST','Atlantic Standard Time','North America','-4'),
('AT','Atlantic Time','North America','-4:00 / -3:00'),
('AoE','Anywhere on Earth','Pacific','-12'),
('BST','Bougainville Standard Time','Pacific','+11'),
('CDT','Central Daylight Time','North America','-5'),
('CHADT','Chatham Island Daylight Time','Pacific','+13:45'),
('CHAST','Chatham Island Standard Time','Pacific','+12:45'),
('CHUT','Chuuk Time','Pacific','+10'),
('CKT','Cook Island Time','Pacific','-10'),
('CT','Central Time','North America','-6:00 / -5:00'),
('ChST','Chamorro Standard Time','Pacific','+10'),
('EASST','Easter Island Summer Time','Pacific','-5'),
('EAST','Easter Island Standard Time','Pacific','-6'),
('EDT','Eastern Daylight Time','North America','-4'),
('EGST','Eastern Greenland Summer Time','North America','+0'),
('EGT','East Greenland Time','North America','-1'),
('EST','Eastern Standard Time','North America','-5'),
('ET','Eastern Time','North America','-5:00 / -4:00'),
('FJST','Fiji Summer Time','Pacific','+13'),
('FJT','Fiji Time','Pacific','+12'),
('GALT','Galapagos Time','Pacific','-6'),
('GAMT','Gambier Time','Pacific','-9'),
('GILT','Gilbert Island Time','Pacific','+12'),
('GMT', 'Greenwich Time','North America','0'),
('HDT','Hawaii-Aleutian Daylight Time','North America','-9'),
('HST','Hawaii Standard Time','North America','-10'),
('HAST','Hawaii-Aleutian Standard Time','Pacific',''),
('KOST','Kosrae Time','Pacific','+11'),
('LINT','Line Islands Time','Pacific','+14'),
('MART','Marquesas Time','Pacific','-9:30'),
('MDT','Mountain Daylight Time','North America','-6'),
('MHT','Marshall Islands Time','Pacific','+12'),
('MST','Mountain Standard Time','North America','-7'),
('MT','Mountain Time','North America','-7:00 / -6:00'),
('NCT','New Caledonia Time','Pacific','+11'),
('NDT','Newfoundland Daylight Time','North America','-2:30'),
('NRT','Nauru Time','Pacific','+12'),
('NST','Newfoundland Standard Time','North America','-3:30'),
('NUT','Niue Time','Pacific','-11'),
('NZDT','New Zealand Daylight Time','Pacific','+13'),
('NZST','New Zealand Standard Time','Pacific','+12'),
('PDT','Pacific Daylight Time','North America','-7'),
('PGT','Papua New Guinea Time','Pacific','+10'),
('PHOT','Phoenix Island Time','Pacific','+13'),
('PMDT','Pierre & Miquelon Daylight Time','North America','-2'),
('PMST','Pierre & Miquelon Standard Time','North America','-3'),
('PONT','Pohnpei Standard Time','Pacific','+11'),
('PST','Pacific Standard Time','North America','-8'),
('PST','Pitcairn Standard Time','Pacific','-8'),
('PT','Pacific Time','North America','-8:00 / -7:00'),
('PWT','Palau Time','Pacific','+9'),
('SBT','Solomon Islands Time','Pacific','+11'),
('SST','Samoa Standard Time','Pacific','-11'),
('TAHT','Tahiti Time','Pacific','-10'),
('TKT','Tokelau Time','Pacific','+13'),
('TOST','Tonga Summer Time','Pacific','+14'),
('TOT','Tonga Time','Pacific','+13'),
('TVT','Tuvalu Time','Pacific','+12'),
('VUT','Vanuatu Time','Pacific','+11'),
('WAKT','Wake Time','Pacific','+12'),
('WFT','Wallis and Futuna Time','Pacific','+12'),
('WGST','Western Greenland Summer Time','North America','-2'),
('WGT','West Greenland Time','North America','-3'),
('WST','West Samoa Time','Pacific','+13'),
('YAPT','Yap Time','Pacific','+10');


